### ISSUE TITLE
Restreindre les droits d'accès du process apache

### ISSUE THREAD

**Issue by equinton** [jancelin/docker-collec#3]
Il vaut mieux limiter les droits au groupe www-data sur l'application :
Plutôt que :
# Droits
  | RUN chown -R www-data:users /var/www/html/collec-master && \
  | chmod -R 755 /var/www/html/collec-master && \
  | chmod -R 777 /var/www/html/collec-master/temp && \
  | chmod -R 777 /var/www/html/collec-master/display/templates_c

il vaut mieux :
chown -R root:www-data collec
chmod -R g+r,g-w collec
chmod -R g+w collec/temp
chmod -R g+w collec/display/templates_c

**Comment by jancelin** [comment]
fait
