### ISSUE TITLE
Problème d'installation sur RPi

### ISSUE THREAD

**Issue by ojsd** [jancelin/docker-collec#4]
Bonjour,

Je rencontre des problèmes pour install Collec-Science sur un Raspberry Pi via Docker

Il s'agit d'une Raspberry Pi 3 B+ sour Raspbian 10 (Buster)
Installation toute fraiche, image "Desktop" montée hier sur carte SD neuve.

J'ai suivi les instruction du Readme, à savoir :

```
sudo -s
apt-get update
apt-get install curl
curl -fsSL https://get.docker.com/ | sh
apt-get install docker-compose
systemctl enable docker
service docker start
groupadd docker
usermod -aG docker $USER

apt-get install wget unzip
wget https://github.com/jancelin/docker-collec/archive/refs/heads/master.zip
unzip master.zip
cd docker-collec-master

docker volume create --name collecpgdata -d local

docker-compose up --build
```
Sortie de `docker-compose up --build`: [docker_compose.txt](https://github.com/jancelin/docker-collec/files/6348960/docker_compose.txt)

Problèmes :

- La dernière commande finit bloquée indéfiniment sur  `LOG:  database system is ready to accept connections` (Cf. log complet dans le fichier ci-dessus)
- Quand je vais à l'adresse indiquée par `docker exec docker-collec-master_collec-web_1 ifconfig` (dans mon cas `172.18.0.2`, je tombe sur l'Apache2 Debian Default Page.
- Quand j'essaie de me connecter à la base avec `psql -U collec -h localhost -p 5433`, j'obtiens : `collec@collec FATAL:  database "collec" does not exist` 

Note : 
Les deux images et les deux containers sont bien présents, mais leur nom diffère de ce qui est noté dans le Readme : moi j'ai `docker-collec-master_collec-web` au lieu de `collec-docker_collec-web` ; cette différence a-t-elle une influence ?

Avez-vous une idée pour débloquer la situation ?

**Comment by equinton** [comment]
Je suis en congés cette semaine, je regarde lundi prochain.

Cordialement,

Eric Quinton

-------- Message d'origine --------

**Comment by equinton** [comment]
Je viens de corriger le code : les chemins d'accès aux fichiers permettant de créer la base de données avaient évolué, mais n'avaient pas été reportés dans l'installation Docker.

Dans le script docker, il faut modifier le fichier db/build-postgres.sh, en corrigeant les lignes 12 et 13 ainsi : 
```
CREATESCRIPT="https://github.com/Irstea/collec/raw/master/install/init_by_psql.sql"
POPULATE="https://github.com/Irstea/collec/raw/master/install/pgsql/collec_create.sql"
```
et relancer l'installation (ou exécuter le script init_by_psql.sql avec psql)

**Comment by ojsd** [comment]
Bonjour,

Merci pour la modif.

Je suis reparti d'une install de Raspberry Pi OS neuve et j'ai relancé les lignes de commandes comme listées dans mon premier message.
Pour info, le log de docker-compose : [log_docker_compose.txt](https://github.com/jancelin/docker-collec/files/6378157/log_docker_compose.txt)

Je peux maintenant me connecter à la base avec `psql -U collec -h localhost -p 5433`, donc ce problème est résolu.

Je peux aussi me connecter à la page web via https://collec-docker.local (non pas directement via `172.18.0.2`, comme je le croyais initialement...) en ajoutant `172.18.0.2 collec-docker collec-docker.local` au fichier `/etc/hosts`. Donc ça c'est réglé aussi.

Par contre, sur la page web, j'ai le message d'erreur suivant, entre le bandeau bleu de menu et les icônes "liste des contenants", "liste des échantillons", etc. :
`La base de données n'est pas dans la version attendue (2.5). Version actuelle :`
(Le message se termine bien comme ça, il n'y a rien après les deux-points).

Merci pour votre aide !

**Comment by equinton** [comment]
Bonjour,

Les tables n'ont pas été créées : la correction du script était incomplète. Il faut récupérer la toute dernière version du script https://github.com/jancelin/docker-collec/raw/master/db/build-postgres.sh qui devrait maintenant fonctionner.

Désolé pour le contretemps, certaines évolutions n'ont pas été toutes testées...

Cordialement,

Éric Q.

**Comment by ojsd** [comment]
Bonjour,

C'est parfait, ça fonctionne, merci !

Seul petit bémol, les noms des images et containers Docker que j'obtiens sont différents de ce qu'il y a dans le ReadMe.
Pour éviter les confusions, il me semble qu'il faudrait soit modifier les scripts pour que les noms correspondent au ReadMe, soit l'inverse.

En effet :

- Readme dit : `collec-docker_collec-web` mais j'obtiens : `docker-collec-master_collec-web`
- Readme dit : `collec-docker_collec-db` mais j'obtiens : `docker-collec-master_collec-db`
- Readme dit : `collec-docker_collec-web_1` mais j'obtiens : `docker-collec-master_collec-web_1`
- Readme dit : `collec-docker_collec-db_1` mais j'obtiens : `docker-collec-master_collec-db_1`

C'est surtout gênant pour les copier-coller de commandes, par exemple dans les chapitres https://github.com/jancelin/docker-collec#docker-is-installed-in-the-computer-that-is-used-to-access-the-application et https://github.com/jancelin/docker-collec#some-useful-docker-commands

**Comment by equinton** [comment]
Merci pour les corrections, je les ai intégrées.
